### ISSUE TITLE
Unable to execute autoIT related script on mac,getting...........Error: dlopen(/Users/569469/Desktop/Project/project-folderIP/autoit/AutoItX3_x64.dll.dylib, 2): image not found 

### ISSUE THREAD

**Issue by monikaSahu** [xhawk18/node-autoit#2]
Hi,

I installed AutoIT on my mac machine globally (tried with locally also).

command used to installed globally:
sudo npm install --save autoit -g

and for locally : sudo npm install --save autoit

and then i wrote some drag and drop code(webdriverio with autoit) using auto it and tried to execute but i am facing below error:
Webdriver io:    http://webdriver.io/api.html

**snippet code:**

            console.log("Step:02 Verify that basedrag element is existing or not");
            aLib.controlClick(client,"//*[@id='dimensionItemHeader0']");
            aLib.controlClick(client,"//*[@id='bopis_code_zv07']");
            rautoit.Init();
            rautoit.MouseClick($MOUSE_CLICK_LEFT)
            rautoit.MouseClickDrag($MOUSE_CLICK_LEFT, 0, 200, 600, 700)

**Error Facing:**
Exception loading: /Users/569469/Desktop/Project/project-folderIP/scripts/Drag_Test.spec.js
[Error: Dynamic Linking Error: dlopen(/Users/569469/Desktop/Project/project-folderIP/autoit/AutoItX3_x64.dll.dylib, 2): image not found]

Please help me to solve this issue.

Thanks,
Monika

**Comment by xhawk18** [comment]
support windows only since autoit only runs on windows.
